package com.asaas.docs.enums;

public enum EventWebhook {

    // Eventos para Cobranças
    PAYMENT_CREATED, PAYMENT_AWAITING_RISK_ANALYSIS, PAYMENT_APPROVED_BY_RISK_ANALYSIS,
    PAYMENT_REPROVED_BY_RISK_ANALYSIS, PAYMENT_AUTHORIZED, PAYMENT_UPDATED, PAYMENT_CONFIRMED, PAYMENT_RECEIVED,
    PAYMENT_CREDIT_CARD_CAPTURE_REFUSED, PAYMENT_ANTICIPATED, PAYMENT_OVERDUE, PAYMENT_DELETED, PAYMENT_RESTORED,
    PAYMENT_REFUNDED, PAYMENT_PARTIALLY_REFUNDED, PAYMENT_REFUND_IN_PROGRESS, PAYMENT_RECEIVED_IN_CASH_UNDONE,
    PAYMENT_CHARGEBACK_REQUESTED, PAYMENT_CHARGEBACK_DISPUTE, PAYMENT_AWAITING_CHARGEBACK_REVERSAL,
    PAYMENT_DUNNING_RECEIVED, PAYMENT_DUNNING_REQUESTED, PAYMENT_BANK_SLIP_VIEWED, PAYMENT_CHECKOUT_VIEWED,
    PAYMENT_SPLIT_CANCELLED, PAYMENT_SPLIT_DIVERGENCE_BLOCK, PAYMENT_SPLIT_DIVERGENCE_BLOCK_FINISHED,

    // Eventos para Assinaturas
    SUBSCRIPTION_CREATED, SUBSCRIPTION_UPDATED, SUBSCRIPTION_INACTIVATED, SUBSCRIPTION_DELETED,
    SUBSCRIPTION_SPLIT_DIVERGENCE_BLOCK, SUBSCRIPTION_SPLIT_DIVERGENCE_BLOCK_FINISHED,

    // Eventos para Notas Fiscais
    INVOICE_CREATED, INVOICE_UPDATED, INVOICE_SYNCHRONIZED, INVOICE_AUTHORIZED, INVOICE_PROCESSING_CANCELLATION,
    INVOICE_CANCELED, INVOICE_CANCELLATION_DENIED, INVOICE_ERROR,

    // Eventos para Transferências
    TRANSFER_CREATED, TRANSFER_PENDING, TRANSFER_IN_BANK_PROCESSING, TRANSFER_BLOCKED, TRANSFER_DONE, TRANSFER_FAILED
    , TRANSFER_CANCELLED,

    // Eventos para Pague Contas
    BILL_CREATED, BILL_PENDING, BILL_BANK_PROCESSING, BILL_PAID, BILL_CANCELLED, BILL_FAILED, BILL_REFUNDED,

    // Eventos para Antecipações
    RECEIVABLE_ANTICIPATION_CANCELLED, RECEIVABLE_ANTICIPATION_SCHEDULED, RECEIVABLE_ANTICIPATION_PENDING,
    RECEIVABLE_ANTICIPATION_CREDITED, RECEIVABLE_ANTICIPATION_DEBITED, RECEIVABLE_ANTICIPATION_DENIED,
    RECEIVABLE_ANTICIPATION_OVERDUE,

    // Eventos para Recargas de Celular
    MOBILE_PHONE_RECHARGE_PENDING, MOBILE_PHONE_RECHARGE_CANCELLED, MOBILE_PHONE_RECHARGE_CONFIRMED,
    MOBILE_PHONE_RECHARGE_REFUNDED,

    // Eventos para Verificação de Situação da conta
    ACCOUNT_STATUS_BANK_ACCOUNT_INFO_APPROVED, ACCOUNT_STATUS_BANK_ACCOUNT_INFO_AWAITING_APPROVAL,
    ACCOUNT_STATUS_BANK_ACCOUNT_INFO_PENDING, ACCOUNT_STATUS_BANK_ACCOUNT_INFO_REJECTED,
    ACCOUNT_STATUS_COMMERCIAL_INFO_APPROVED, ACCOUNT_STATUS_COMMERCIAL_INFO_AWAITING_APPROVAL,
    ACCOUNT_STATUS_COMMERCIAL_INFO_PENDING, ACCOUNT_STATUS_COMMERCIAL_INFO_REJECTED, ACCOUNT_STATUS_DOCUMENT_APPROVED
    , ACCOUNT_STATUS_DOCUMENT_AWAITING_APPROVAL, ACCOUNT_STATUS_DOCUMENT_PENDING, ACCOUNT_STATUS_DOCUMENT_REJECTED,
    ACCOUNT_STATUS_GENERAL_APPROVAL_APPROVED, ACCOUNT_STATUS_GENERAL_APPROVAL_AWAITING_APPROVAL,
    ACCOUNT_STATUS_GENERAL_APPROVAL_PENDING, ACCOUNT_STATUS_GENERAL_APPROVAL_REJECTED

}
