package com.asaas.docs.enums;

public enum TransactionStatus {

    AWAITING_BALANCE_VALIDATION, AWAITING_INSTANT_PAYMENT_ACCOUNT_BALANCE, AWAITING_CRITICAL_ACTION_AUTHORIZATION,
    AWAITING_CHECKOUT_RISK_ANALYSIS_REQUEST, AWAITING_CASH_IN_RISK_ANALYSIS_REQUEST, SCHEDULED, AWAITING_REQUEST,
    REQUESTED, DONE, REFUSED, CANCELLED

}
